<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'vdomah\\jwtauth\\Plugin' => 'plugins\\vdomah\\jwtauth\\Plugin.php',
  'rainlab\\user\\Plugin' => 'plugins\\rainlab\\user\\Plugin.php',
  'RainLab\\User\\Models\\User' => 'plugins\\rainlab\\user\\models\\User.php',
  'RainLab\\User\\Models\\UserGroup' => 'plugins\\rainlab\\user\\models\\UserGroup.php',
  'RainLab\\User\\Classes\\UserRedirector' => 'plugins\\rainlab\\user\\classes\\UserRedirector.php',
  'Vdomah\\JWTAuth\\Classes\\JWTAuthServiceProvider' => 'plugins\\vdomah\\jwtauth\\classes\\JWTAuthServiceProvider.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'October\\Demo\\Components\\Todo' => 'plugins\\october\\demo\\components\\Todo.php',
  'RainLab\\User\\Components\\Session' => 'plugins\\rainlab\\user\\components\\Session.php',
  'RainLab\\User\\Components\\Account' => 'plugins\\rainlab\\user\\components\\Account.php',
  'RainLab\\User\\Components\\ResetPassword' => 'plugins\\rainlab\\user\\components\\ResetPassword.php',
);